"""
Tests for src/bmspace/bms.py

The BMS command functions are tested using a mock transport that injects
pre-built response fixtures.  No real hardware or network is required.
"""
from __future__ import annotations

from unittest.mock import MagicMock

import pytest

from bmspace.bms import (
    PackAnalogData,
    PackCapacity,
    PackWarnInfo,
    get_analog_data,
    get_pack_capacity,
    get_serial,
    get_version,
    get_warn_info,
)


# ---------------------------------------------------------------------------
# Fixtures – pre-built valid response packets
# (generated by the helper in test_protocol.py / computed offline)
# ---------------------------------------------------------------------------

# Version: "BMS V1.0"
# INFO = hex-encoded ASCII "BMS V1.0" = 424D532056312E30 (16 chars, LENID=010)
VERSION_RESPONSE = b"~25014600F010424D532056312E30FA46\r"

# Serial: BMS SN = "BMS001234567", Pack SN = "PCK9876543"
# INFO[0:30] = bms_sn as hex, INFO[30:40] = gap, INFO[40:68] = pack_sn as hex
SERIAL_RESPONSE = b"~250146008044424D53303031323334353637202020000000000050434B3938373635343320202020F012\r"

# Analog: 1 pack, 2 cells (3300, 3310 mV), 2 temps (25.0, 20.0 °C),
#   i_pack=10.0 A, v_pack=51.2 V, i_remain=10000 mAh, i_full=20000 mAh,
#   cycles=42, i_design=20000 mAh → SOC=50.0%, SOH=100.0%
# INFO: DATAFLG(00) + packs(01) + cells(02) + cell1(0CE4) + cell2(0CEE)
#      + temps(02) + temp1(0BA4) + temp2(0B72) + i_pack(03E8) + v_pack(C800)
#      + i_remain(03E8) + P(03) + i_full(07D0) + cycles(002A) + i_design(07D0) + reserved(00)
ANALOG_RESPONSE = b"~2501460090340001020CE40CEE020BA40B7203E8C80003E80307D0002A07D000F287\r"

# Pack capacity: remain=10000, full=20000, design=20000 mAh
CAPACITY_RESPONSE = b"~25014600400C03E807D007D0FB01\r"

# Warn: 1 pack, 2 cells (no cell/temp warnings), instruction=0x06 → charge_fet=1, discharge_fet=1
# INFO: DATAFLG(00) + pack_count_echo(01) + cells(02) + cell1(00) + cell2(00)
#      + temps(02) + temp1(00) + temp2(00) + charge_cur(00) + total_volt(00) + disch_cur(00)
#      + protect1(00) + protect2(00) + instruction(06) + control(00) + fault(00)
#      + balance1(00) + balance2(00) + warn1(00) + warn2(00)
WARN_RESPONSE = b"~2501460060280001020000020000000000000006000000000000F613\r"


def _mock_transport(response: bytes) -> MagicMock:
    """Return a mock transport that returns *response* from receive()."""
    transport = MagicMock()
    transport.receive.return_value = response
    return transport


def _mock_transport_sequence(*responses: bytes) -> MagicMock:
    """Return a mock transport that cycles through *responses* in order."""
    transport = MagicMock()
    transport.receive.side_effect = list(responses)
    return transport


# ---------------------------------------------------------------------------
# get_version
# ---------------------------------------------------------------------------


class TestGetVersion:
    def test_returns_version_string(self):
        transport = _mock_transport(VERSION_RESPONSE)
        version = get_version(transport)
        assert version == "BMS V1.0"

    def test_sends_exactly_one_request(self):
        transport = _mock_transport(VERSION_RESPONSE)
        get_version(transport)
        transport.send.assert_called_once()

    def test_raises_on_error_response(self):
        # Craft a response with RTN=04 (CID2 undefined)
        error_resp = b"~250146004" + b"0" + b"000" + b"FFFF\r"
        transport = _mock_transport(error_resp)
        with pytest.raises(RuntimeError):
            get_version(transport)


# ---------------------------------------------------------------------------
# get_serial
# ---------------------------------------------------------------------------


class TestGetSerial:
    def test_returns_bms_and_pack_sn(self):
        transport = _mock_transport(SERIAL_RESPONSE)
        bms_sn, pack_sn = get_serial(transport)
        assert bms_sn == "BMS001234567"
        assert pack_sn == "PCK9876543"

    def test_raises_on_protocol_error(self):
        transport = _mock_transport(b"GARBAGE\r")
        with pytest.raises(RuntimeError):
            get_serial(transport)


# ---------------------------------------------------------------------------
# get_analog_data
# ---------------------------------------------------------------------------


class TestGetAnalogData:
    def test_returns_list_with_one_pack(self):
        transport = _mock_transport(ANALOG_RESPONSE)
        packs = get_analog_data(transport)
        assert len(packs) == 1

    def test_pack_number(self):
        transport = _mock_transport(ANALOG_RESPONSE)
        pack = get_analog_data(transport)[0]
        assert pack.pack_number == 1

    def test_cell_voltages(self):
        transport = _mock_transport(ANALOG_RESPONSE)
        pack = get_analog_data(transport)[0]
        assert pack.cells == [3300, 3310]

    def test_cell_max_diff(self):
        transport = _mock_transport(ANALOG_RESPONSE)
        pack = get_analog_data(transport)[0]
        assert pack.cells_max_diff == 10  # 3310 - 3300

    def test_temperatures(self):
        transport = _mock_transport(ANALOG_RESPONSE)
        pack = get_analog_data(transport)[0]
        assert pack.temps == [25.0, 20.0]

    def test_current(self):
        transport = _mock_transport(ANALOG_RESPONSE)
        pack = get_analog_data(transport)[0]
        assert pack.i_pack == pytest.approx(10.0)

    def test_voltage(self):
        transport = _mock_transport(ANALOG_RESPONSE)
        pack = get_analog_data(transport)[0]
        assert pack.v_pack == pytest.approx(51.2)

    def test_remaining_capacity(self):
        transport = _mock_transport(ANALOG_RESPONSE)
        pack = get_analog_data(transport)[0]
        assert pack.i_remain_cap == 10000

    def test_full_capacity(self):
        transport = _mock_transport(ANALOG_RESPONSE)
        pack = get_analog_data(transport)[0]
        assert pack.i_full_cap == 20000

    def test_soc(self):
        transport = _mock_transport(ANALOG_RESPONSE)
        pack = get_analog_data(transport)[0]
        assert pack.soc == pytest.approx(50.0)

    def test_cycles(self):
        transport = _mock_transport(ANALOG_RESPONSE)
        pack = get_analog_data(transport)[0]
        assert pack.cycles == 42

    def test_design_capacity(self):
        transport = _mock_transport(ANALOG_RESPONSE)
        pack = get_analog_data(transport)[0]
        assert pack.i_design_cap == 20000

    def test_soh(self):
        transport = _mock_transport(ANALOG_RESPONSE)
        pack = get_analog_data(transport)[0]
        assert pack.soh == pytest.approx(100.0)

    def test_negative_current(self):
        """Values >= 32768 should be interpreted as negative (charging)."""
        from bmspace.protocol import chksum_calc, lchksum_calc

        def _make_analog_response(i_pack_raw: int) -> bytes:
            cell1, cell2 = 3300, 3310
            temp1_raw = 25 * 10 + 2730
            temp2_raw = 20 * 10 + 2730
            v_pack_raw = 51200
            i_remain_raw = 1000
            i_full_raw = 2000
            info_str = (
                "00"    # DATAFLG
                "01"    # pack count = 1
                "02"    # cells = 2
                + format(cell1, "04X")
                + format(cell2, "04X")
                + "02"
                + format(temp1_raw, "04X")
                + format(temp2_raw, "04X")
                + format(i_pack_raw, "04X")
                + format(v_pack_raw, "04X")
                + format(i_remain_raw, "04X")
                + "03"
                + format(i_full_raw, "04X")
                + format(42, "04X")
                + format(2000, "04X")
                + "00"
            )
            soi = b"~"; ver = b"25"; adr = b"01"; cid1 = b"46"; rtn = b"00"
            info = info_str.encode("ASCII")
            lenid = bytes(format(len(info), "03X"), "ASCII")
            lchksum = bytes(lchksum_calc(lenid), "ASCII")
            packet = soi + ver + adr + cid1 + rtn + lchksum + lenid + info
            return packet + bytes(chksum_calc(packet), "ASCII") + b"\r"

        # 5.0 A discharge → raw = 500
        transport = _mock_transport(_make_analog_response(500))
        pack = get_analog_data(transport)[0]
        assert pack.i_pack == pytest.approx(5.0)

        # −5.0 A charge: protocol: -1 * (65535 - raw) / 100 = -5.0
        # → 65535 - raw = 500 → raw = 65035
        raw_neg = 65035
        transport = _mock_transport(_make_analog_response(raw_neg))
        pack = get_analog_data(transport)[0]
        assert pack.i_pack == pytest.approx(-5.0)

    def test_raises_on_protocol_error(self):
        transport = _mock_transport(b"~250146040" + b"0000" + b"FFFF\r")
        with pytest.raises(RuntimeError):
            get_analog_data(transport)

    def test_returns_dataclass_instances(self):
        transport = _mock_transport(ANALOG_RESPONSE)
        packs = get_analog_data(transport)
        assert all(isinstance(p, PackAnalogData) for p in packs)


# ---------------------------------------------------------------------------
# get_pack_capacity
# ---------------------------------------------------------------------------


class TestGetPackCapacity:
    def test_returns_pack_capacity(self):
        transport = _mock_transport(CAPACITY_RESPONSE)
        cap = get_pack_capacity(transport)
        assert isinstance(cap, PackCapacity)

    def test_remain_capacity(self):
        transport = _mock_transport(CAPACITY_RESPONSE)
        cap = get_pack_capacity(transport)
        assert cap.remain_cap == 10000

    def test_full_capacity(self):
        transport = _mock_transport(CAPACITY_RESPONSE)
        cap = get_pack_capacity(transport)
        assert cap.full_cap == 20000

    def test_design_capacity(self):
        transport = _mock_transport(CAPACITY_RESPONSE)
        cap = get_pack_capacity(transport)
        assert cap.design_cap == 20000

    def test_soc(self):
        transport = _mock_transport(CAPACITY_RESPONSE)
        cap = get_pack_capacity(transport)
        assert cap.soc == pytest.approx(50.0)

    def test_soh(self):
        transport = _mock_transport(CAPACITY_RESPONSE)
        cap = get_pack_capacity(transport)
        assert cap.soh == pytest.approx(100.0)

    def test_raises_on_protocol_error(self):
        transport = _mock_transport(b"GARBAGE\r")
        with pytest.raises(RuntimeError):
            get_pack_capacity(transport)


# ---------------------------------------------------------------------------
# get_warn_info
# ---------------------------------------------------------------------------


class TestGetWarnInfo:
    def test_returns_list_with_one_entry(self):
        transport = _mock_transport(WARN_RESPONSE)
        warn_list = get_warn_info(transport, packs=1)
        assert len(warn_list) == 1

    def test_returns_pack_warn_info_instances(self):
        transport = _mock_transport(WARN_RESPONSE)
        warn_list = get_warn_info(transport, packs=1)
        assert all(isinstance(w, PackWarnInfo) for w in warn_list)

    def test_pack_number(self):
        transport = _mock_transport(WARN_RESPONSE)
        warn = get_warn_info(transport, packs=1)[0]
        assert warn.pack_number == 1

    def test_no_warnings_when_all_normal(self):
        transport = _mock_transport(WARN_RESPONSE)
        warn = get_warn_info(transport, packs=1)[0]
        assert warn.warnings == ""

    def test_charge_fet_on(self):
        # Instruction byte = 0x06 = 0b00000110 → bit1=charge_fet, bit2=discharge_fet
        transport = _mock_transport(WARN_RESPONSE)
        warn = get_warn_info(transport, packs=1)[0]
        assert warn.charge_fet == 1

    def test_discharge_fet_on(self):
        transport = _mock_transport(WARN_RESPONSE)
        warn = get_warn_info(transport, packs=1)[0]
        assert warn.discharge_fet == 1

    def test_current_limit_off(self):
        # Instruction byte = 0x06, bit0 = current_limit = 0
        transport = _mock_transport(WARN_RESPONSE)
        warn = get_warn_info(transport, packs=1)[0]
        assert warn.current_limit == 0

    def test_no_protection_flags_set(self):
        transport = _mock_transport(WARN_RESPONSE)
        warn = get_warn_info(transport, packs=1)[0]
        assert warn.prot_short_circuit == 0
        assert warn.prot_discharge_current == 0
        assert warn.prot_charge_current == 0

    def test_balancing_all_zeros(self):
        transport = _mock_transport(WARN_RESPONSE)
        warn = get_warn_info(transport, packs=1)[0]
        assert warn.balancing1 == "00000000"
        assert warn.balancing2 == "00000000"

    def test_raises_on_protocol_error(self):
        transport = _mock_transport(b"GARBAGE\r")
        with pytest.raises(RuntimeError):
            get_warn_info(transport, packs=1)
